arki55/features/T9-github-build-checks-libspectrum chore: Added fake steps to some builds so that all of them have the same logical steps. feat:  Added assertion of output from configure, to make sure we are building the right setup.

diff --git a/.github/workflows/build_linux.yml b/.github/workflows/build_linux.yml
--- a/.github/workflows/build_linux.yml
+++ b/.github/workflows/build_linux.yml
@@ -1,43 +1,57 @@
 name: Fuse Libspectrum Linux Build
-run-name: Build Libspectrum for Linux / ${{ github.actor }} /
+run-name: Build and test Libspectrum for Linux / ${{ github.actor }} /
 on: [push]
 jobs:
   build:
     name: Build Fuse Libspectrum for Linux
     runs-on: ubuntu-latest
     steps:
-      - name: (1) Check out repository code
+      - name: (1) Prepare git
+        run: |
+          echo "Not needed in this build"
+
+      - name: (2) Check out repository code
         uses: actions/checkout@v3
 
-      - name: (2) Install dependencies
+      - name: (3) Install dependencies
         run: |
           echo "Installing dependencies .."
+          echo "No dependencies in this build"
 
-      - name: (3) Autogen.sh
+      - name: (4) Autogen.sh
         run: |
           echo "Running autogen.sh .."
           ./autogen.sh
 
-      - name: (4) Configure for linux
+      - name: (5) Configure for linux (real glib)
         run: |
           echo "Running configure .."
-          ./configure
+          ./configure | tee ./configure.out
 
-      - name: (5) Make
+      - name: (6) Verify output from configure
+        run: |
+          message1="Internal GLib replacement: no"
+          lines1=(`cat "./configure.out" | grep -c "$message1"`)
+          if [[ "$lines1" -ne "1" ]]; then
+            echo "Error: Message $message1 not found!"
+            exit 1
+          fi
+
+      - name: (7) Make
         run: |
           echo "Running make .."
           make
 
-      - name: (6) Install (+sudo)
+      - name: (8) Install (+sudo)
         run: |
           echo "Running make install .."
           sudo make install
 
-      - name: (7) Run tests
+      - name: (9) Run tests
         run: |
           echo "Bulding and running tests .."
           make check
 
-      - name: (8) Finish
+      - name: (10) Finish
         run: |
           echo "🍏 Finishing with status ${{ job.status }}."
diff --git a/.github/workflows/build_wii.yml b/.github/workflows/build_wii.yml
--- a/.github/workflows/build_wii.yml
+++ b/.github/workflows/build_wii.yml
@@ -19,28 +19,38 @@ jobs:
         run: |
           echo "(not) Running autogen.sh .."
 
-      - name: (4) Configure for WII
+      - name: (4) Configure for WII (fake glib)
         run: |
           echo "Running configure for WII .."
           ./configure --target=powerpc-gekko --host=powerpc-gekko \
             --prefix=$DEVKITPPC \
-            --without-libgcrypt --with-fake-glib --without-libaudiofile
+            --without-libgcrypt --with-fake-glib --without-libaudiofile \
+            | tee ./configure.out
 
-      - name: (5) Make
+      - name: (5) Verify output from configure
+        run: |
+          message1="Internal GLib replacement: yes"
+          lines1=(`cat "./configure.out" | grep -c "$message1"`)
+          if [[ "$lines1" -ne "1" ]]; then
+            echo "Error: Message $message1 not found!"
+            exit 1
+          fi
+
+      - name: (6) Make
         run: |
           echo "Running make .."
           make
 
-      - name: (6) Install (+sudo)
+      - name: (7) Install (+sudo)
         run: |
           echo "Running make install .."
           sudo make install
 
-      - name: (7) Run tests
+      - name: (8) Run tests
         run: |
           echo "Bulding and running tests .."
           make check
 
-      - name: (8) Finish
+      - name: (9) Finish
         run: |
           echo "🍏 Finishing with status ${{ job.status }}."
diff --git a/.github/workflows/build_windows.yml b/.github/workflows/build_windows.yml
--- a/.github/workflows/build_windows.yml
+++ b/.github/workflows/build_windows.yml
@@ -14,7 +14,7 @@ jobs:
       - name: (2) Check out repository code
         uses: actions/checkout@v3
 
-      - name: (3) Install Cygwin (32 bit) with libs
+      - name: (3) Install dependencies - Cygwin (32 bit) with libs
         uses: cygwin/cygwin-install-action@master
         with:
           platform: x86
@@ -42,7 +42,7 @@ jobs:
       - name: (4) Autogen.sh
         run: bash ./autogen.sh
 
-      - name: (5) Configure for Windows
+      - name: (5) Configure for Windows (fake glib)
         run: bash ./configure \
               --build=i686-pc-cygwin \
               --host=i686-w64-mingw32 \
@@ -50,15 +50,24 @@ jobs:
               --disable-static \
               --with-fake-glib
 
-      - name: (6) Make
+      - name: (6) Verify output from configure
+        run: bash |
+          message1="Internal GLib replacement: yes"
+          lines1=(`cat "./configure.out" | grep -c "$message1"`)
+          if [[ "$lines1" -ne "1" ]]; then
+            echo "Error: Message $message1 not found!"
+            exit 1
+          fi
+
+      - name: (7) Make
         run: make
 
-      - name: (7) Install
+      - name: (8) Install
         run: make install-strip
 
-      - name: (8) Run tests
+      - name: (9) Run tests
         run: make check
 
-      - name: (9) Finish
+      - name: (10) Finish
         run: |
           echo "🍏 Finishing with status ${{ job.status }}."
